# -*- coding: utf-8 -*-
"""5G-Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVokjrf9QidvTgiGApi_pFFgHVebn6_s

# **Khai báo các thư viện sử dụng**
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelBinarizer
from sklearn.utils.class_weight import compute_class_weight
import seaborn as sns
import time
import datetime
import pytz
from joblib import dump
import warnings
import numpy as np
warnings.filterwarnings('ignore')

""":# **Xem nội dung của dataset và chọn lọc 25 trường thông tin**

Xem các cột có trong dataset
"""

file_path_full = '/content/drive/MyDrive/5G_model/Dataset_5G-NIDD_Encoded.csv'

df_full = pd.read_csv(file_path_full, low_memory=False)
df_full = df_full.drop(columns=['Unnamed: 0'], errors='ignore')
num_samples = df_full.shape[0]
num_columns = df_full.shape[1]

print(f"- Số lượng mẫu: {num_samples}")
print(f"- Số lượng cột: {num_columns}")
print("- Danh sách các cột:", df_full.columns.tolist())
cols = df_full.columns.tolist()
for i in range(0, len(cols), 15):
    print("  " + " | ".join(cols[i:i+15]))

"""Chọn các trường thông tin và tạo 1 dataset mới từ các trường đó"""

selected_columns = ['tcp', 'AckDat', 'sHops', 'Seq', 'RST', 'TcpRtt', 'REQ', 'dMeanPktSz','Offset', 'CON', 'FIN', 'sTtl', ' e        ', 'INT', 'Mean', 'Status', 'icmp',
 'SrcTCPBase', ' e d      ', 'sMeanPktSz', 'DstLoss', 'Loss', 'dTtl', 'SrcBytes', 'TotBytes', 'Label', 'Attack Type', 'Attack Tool']
existing_columns = [column for column in selected_columns if column in df_full.columns]
df_selected = df_full[existing_columns].copy()
output_path = '/content/drive/MyDrive/5G_model/Dataset_Using.csv'
df_selected.to_csv(output_path, index=False)

print(f"-- Result : Dataset mới đã được lưu tại {output_path}")

"""# **Xem thông tin của dataset mới vừa tạo**"""

file_path = '/content/drive/MyDrive/5G_model/Dataset_Using.csv'
df = pd.read_csv(file_path, low_memory=False)
df = df.drop(columns=['Unnamed: 0'], errors='ignore')
num_samples = df.shape[0]
num_columns = df.shape[1]
num_benign = df[df["Label"] == "Benign"].shape[0]
num_malicious = df[df["Label"] != "Benign"].shape[0]
num_dif_benign_malicious = num_benign/num_malicious

print(f"- Số lượng mẫu: {num_samples}")
print(f"- Số lượng cột: {num_columns}")
print("- Danh sách các cột:", df.columns.tolist())
# In mỗi hàng 10 cột
cols = df.columns.tolist()
for i in range(0, len(cols), 15):
    print("  " + " | ".join(cols[i:i+15]))
print(f"- Số lượng benign traffic: {num_benign}")
print(f"- Số lượng malicious traffic: {num_malicious}")
print(f"- Độ chênh lệnh giữa benign và malicious: {num_dif_benign_malicious}")

print(df.info())

df["Attack Type"].value_counts()

"""So sánh"""

percent_benign = (num_benign/num_samples) * 100
percent_malicious = (num_malicious/num_samples) * 100
labels = ['Benign', 'Malicious']
sizes = [percent_benign, percent_malicious]
colors = ['#90EE90','#20B2AA']
explode = (0,0)

plt.figure(figsize=(4,3))
plt.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.2f%%',startangle=90)
plt.axis('equal')
plt.title('Comparison of Benign and Malicious')
plt.show()

"""# **Split data và xử lí dữ liệu bị thiếu**
- Xóa dữ liệu bị thiếu
- Xóa các cột IP

=> Giữ lại khiến mô hình dễ phụ thuộc thay vì phân tích lưu lượng.
- Thực hiện Pearson Correlation: loại bỏ các đặc trưng dư thừa, có nghĩa là các đặc trưng tương quan cao, mang thông tin giống nhau. Chỉ giữ lại một đặc trưng duy nhất.
- Thực hiện phân tích ANOVA F-scores: đưa ra 25 trường có ảnh hưởng cao nhất đến kết quả.

**Chia dữ liệu train/set**
"""

# Handle missing values
print("\n🧹 Handling missing values...")
# Replace infinities with NaN so they can be caught by the imputer
df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Fill NaN values for numeric columns with median
numerical_columns = df.select_dtypes(include=np.number).columns
df[numerical_columns] = df[numerical_columns].fillna(df[numerical_columns].median())

# Fill NaN values for categorical columns with mode
categorical_columns = df.select_dtypes(exclude=np.number).columns
for col in categorical_columns:
    if df[col].isna().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

# Verify NaN values are handled
print("\n📊 Missing values after preprocessing:")
print(df.isna().sum().sum(), "total NaN values remaining")

df['Multiclass_Label'] = df['Label'] + "_" + df['Attack Type'] + "_" + df['Attack Tool']
X = df.drop(columns=["Label", "Attack Type", "Attack Tool", "Multiclass_Label"])
y = df["Multiclass_Label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)
print("Train set size:",len(X_train))
print("Phân phối Label trong Train set:")
print(y_train.value_counts(normalize=True))
print("-"*50)
print("Test set size:",len(X_test))
print("Phân phối Label trong Test set:")
print(y_test.value_counts(normalize=True))

"""**Kiểm tra dữ liệu bị thiếu**"""

def check_missing_values(df):
    missing_values = df.isnull().sum()
    missing_percentage = (missing_values / len(df)) * 100

    missing_df = pd.DataFrame({'Missing Values': missing_values, 'Percentage': missing_percentage})
    missing_df = missing_df[missing_df['Missing Values'] > 0].sort_values(by='Missing Values', ascending=False)

    if missing_df.empty:
        print("Không có giá trị bị thiếu trong dataset.")
    else:
        print(missing_df)
        # Vẽ biểu đồ trực quan hóa dữ liệu bị thiếu
        plt.figure(figsize=(10, 5))
        missing_df['Missing Values'].plot(kind='bar', color='red')
        plt.title('Số lượng giá trị bị thiếu trong mỗi cột')
        plt.xlabel('Cột')
        plt.ylabel('Số lượng')
        plt.xticks(rotation=45)
        plt.show()

print("--- Kiểm tra ở trainning set ---")
check_missing_values(X_train)

for col in ['dTtl', 'SrcTCPBase', 'sTtl', 'sHops']:
    X_train[col].fillna(-1, inplace=True)
    X_test[col].fillna(-1, inplace=True)
check_missing_values(X_train)

"""# **Xây dựng mô hình random forest**

Tạo model
"""

from google.colab import files
# Khởi tạo mô hình
print("\n🔧 Training Random Forest model...")
# Ghi nhận thời gian bắt đầu
start_time = time.time()
print("\n⚖️ Computing class weights...")
class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
class_weight_dict = dict(zip(np.unique(y_train), class_weights))
# Train the model with class weights
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=30,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight=class_weight_dict,
    random_state=42
)
# Huấn luyện mô hình
rf_model.fit(X_train, y_train)
# Thêm tập validation
# Ghi nhận thời gian kết thúc
end_time = time.time()
execution_time = end_time - start_time

print(f"⏱️ Thời gian huấn luyện: {execution_time:.2f} giây")
dump(rf_model, 'my_rf_model.joblib')

"""Tiến hành đánh giá model và tải xuống model"""

#files.download('my_rf_model.joblib')
print("Download model successful")
y_pred = rf_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

lb = LabelBinarizer()
y_test_binarized = lb.fit_transform(y_test)
y_pred_proba = rf_model.predict_proba(X_test)

if isinstance(y_pred_proba, list):
    y_pred_proba = y_pred_proba[0]

try:
    roc_auc = roc_auc_score(y_test_binarized, y_pred_proba, average="weighted", multi_class="ovr")
except ValueError:
    roc_auc = None

print("\n🎯 Đánh giá mô hình Random Forest:")
print(f"- Accuracy     : {accuracy:.4f}")
print(f"- Precision    : {precision:.4f}")
print(f"- Recall       : {recall:.4f}")
print(f"- F1-score     : {f1:.4f}")
print(f"- ROC AUC      : {roc_auc:.4f}" if roc_auc else "- ROC AUC      : Không tính được với dữ liệu này")
print(f"- Execution Time: {execution_time:.2f} giây")

# Generate detailed classification report
print("\n📝 Detailed Classification Report:")
print(classification_report(y_test, y_pred))

"""Đánh giá bằng Confusion Matrix"""

# Lấy danh sách các nhãn duy nhất
labels = np.unique(np.concatenate((y_test, y_pred)))

# Tạo confusion matrix
cm = confusion_matrix(y_test, y_pred, labels=labels)

# Tạo DataFrame cho confusion matrix để dễ hiển thị
cm_df = pd.DataFrame(cm, index=labels, columns=labels)

# Vẽ heatmap của confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm_df, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix', fontsize=14)
plt.ylabel('Actual Labels', fontsize=12)
plt.xlabel('Predicted Labels', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()
print('='*200)
# Tạo normalized confusion matrix (tỷ lệ phần trăm)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
cm_normalized_df = pd.DataFrame(cm_normalized, index=labels, columns=labels)

# Vẽ heatmap của normalized confusion matrix
plt.figure(figsize=(12, 10))
sns.heatmap(cm_normalized_df, annot=True, fmt='.1%', cmap='Blues', cbar=False)
plt.title('Percentage Confusion Matrix', fontsize=14)
plt.ylabel('Actual Labels', fontsize=12)
plt.xlabel('Predicted Labels', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.savefig('normalized_confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# Data tự input
# sample_dict = [
#     {
#         'tcp': 0, 'AckDat': 0, 'sHops': 1, 'Seq': 47138, 'RST': 0, 'TcpRtt': 0, 'REQ': 1,
#         'dMeanPktSz': 0, 'Offset': 19272380, 'CON': 0, 'FIN': 0, 'sTtl': 63, ' e        ': 1,
#         'INT': 0, 'Mean': 2.582307, 'Status': 1, 'icmp': 0, 'SrcTCPBase': -1, ' e d      ': 0,
#         'sMeanPktSz': 42, 'DstLoss': 0, 'Loss': 0, 'dTtl': -1, 'SrcBytes': 84, 'TotBytes': 84
#     },
#     {
#         'tcp': 1, 'AckDat': 0, 'sHops': 10, 'Seq': 20000, 'RST': 0, 'TcpRtt': 12, 'REQ': 0,
#         'dMeanPktSz': 500, 'Offset': 10000, 'CON': 0, 'FIN': 0, 'sTtl': 64, ' e        ': 0,
#         'INT': 20, 'Mean': 1.2, 'Status': 0, 'icmp': 0, 'SrcTCPBase': 0, ' e d      ': 0,
#         'sMeanPktSz': 512, 'DstLoss': 0, 'Loss': 0, 'dTtl': 64, 'SrcBytes': 1024, 'TotBytes': 2048
#     },
#         {
#         'tcp': 1, 'AckDat': 0.024088, 'sHops': 1, 'Seq': 17276, 'RST': 0, 'TcpRtt': 0.026046, 'REQ': 0,
#         'dMeanPktSz': 66, 'Offset': 10098024, 'CON': 0, 'FIN': 1, 'sTtl': 63, ' e        ': 1,
#         'INT': 0, 'Mean': 0, 'Status': 1, 'icmp': 0, 'SrcTCPBase': 4238886840, ' e d      ': 0,
#         'sMeanPktSz': 66, 'DstLoss': 0, 'Loss': 0, 'dTtl': 59, 'SrcBytes': 66, 'TotBytes': 132
#     }
# ]
# sample_df = pd.DataFrame(sample_dict)
# sample_df = sample_df[X_train.columns]
# sample_df = sample_df.fillna(0)

# Data lấy csv chỉ đủ 28
csv_data = pd.read_csv('/content/drive/MyDrive/5G_model/4_Records_Test.csv')

# Loại bỏ 3 cột không cần thiết
columns_to_drop = ['Label', 'Attack Tool', 'Attack Type']
csv_data = csv_data.drop(columns=columns_to_drop, errors='ignore')

# Lấy các cột phù hợp với tập huấn luyện
csv_data = csv_data[X_train.columns]

# Xử lý dữ liệu thiếu
csv_data = csv_data.fillna(0)

# Tiếp tục với dự đoán
y_preds = rf_model.predict(csv_data)
# Hiển thị kết quả
print("\nKết quả dự đoán các mẫu:")
for idx, y_pred in enumerate(y_preds):
    try:
        label, attack_type, tool = y_pred.split('_')
    except:
        label, attack_type, tool = y_pred, 'Unknown', 'Unknown'
    current_time = datetime.datetime.now(pytz.timezone('Etc/GMT-7')).strftime("%H:%M:%S-%d/%m/%Y")
    print(f"Mẫu {idx+1} with [{current_time}]:")
    print(f"  - Label        : {label}")
    print(f"  - Attack Type  : {attack_type}")
    print(f"  - Attack Tool  : {tool}\n")

# Đọc file CSV
csv_data = pd.read_csv('/content/drive/MyDrive/5G_model/Dataset_5G-NIDD_Encoded.csv')

# Loại bỏ 3 cột không cần thiết
columns_to_drop = ['Label', 'Attack Tool', 'Attack Type']
csv_data = csv_data.drop(columns=columns_to_drop, errors='ignore')

# Chỉ chọn các cột cần thiết cho mô hình
csv_data = csv_data[X_train.columns]

# Xử lý dữ liệu thiếu
csv_data = csv_data.fillna(0)

# Tiếp tục với dự đoán
y_preds = rf_model.predict(csv_data)

# Hiển thị kết quả
print("\nKết quả dự đoán các mẫu:")
for idx, y_pred in enumerate(y_preds):
    try:
        label, attack_type, tool = y_pred.split('_')
    except:
        label, attack_type, tool = y_pred, 'Unknown', 'Unknown'
    current_time = datetime.datetime.now(pytz.timezone('Etc/GMT-7')).strftime("%H:%M:%S-%d/%m/%Y")
    print(f"Mẫu {idx+1} with [{current_time}]:")
    print(f"  - Label        : {label}")
    print(f"  - Attack Type  : {attack_type}")
    print(f"  - Attack Tool  : {tool}\n")